In [28]:
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
data = pd.read_html(url)
df = data[0]
symbols = df['Symbol'].head(100).tolist()

In [29]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: yfinance in /usr/local/lib/python3.9/dist-packages (0.2.12)
Requirement already satisfied: cryptography>=3.3.2 in /usr/local/lib/python3.9/dist-packages (from yfinance) (39.0.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.9/dist-packages (from yfinance) (4.11.2)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.9/dist-packages (from yfinance) (1.1)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.9/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.9/dist-packages (from yfinance) (2.3.5)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.9/dist-packages (from yfinance) (1.22.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.9/dist-packages (from yfinance) (2022.7.1)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.9/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.9/dist-packages (from yfinance) (2.28.2)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.9/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.9/dist-packages (from yfinance) (4.9.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.9/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.9/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.26->yfinance) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.26->yfinance) (1.26.15)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)

In [30]:
import yfinance as yf

df = pd.DataFrame()

for symbol in symbols:
    data = yf.download(symbol, start="2004-01-01", end="2023-01-01")
    data['Symbol'] = symbol
    df = pd.concat([df, data])

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BRK.B: No timezone found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BF.B: No data found for this date range, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [31]:
df

,Open,High,Low,Close,Adj Close,Volume,Symbol
Date,,,,,,,
2004-01-02,85.000000,85.190002,83.110001,83.370003,49.130291,2591700.0,MMM
2004-01-05,83.580002,85.000000,83.320000,84.959999,50.067272,2985200.0,MMM
2004-01-06,84.500000,84.959999,84.400002,84.699997,49.914070,2983100.0,MMM
2004-01-07,84.120003,84.250000,82.699997,83.239998,49.053661,4293600.0,MMM
2004-01-08,83.239998,83.250000,82.379997,82.680000,48.723644,3489300.0,MMM
...,...,...,...,...,...,...,...
2022-12-23,30.250000,30.700001,30.190001,30.690001,30.490850,2126300.0,CNP
2022-12-27,30.740000,31.010000,30.590000,30.920000,30.719357,1364800.0,CNP
2022-12-28,30.950001,31.150000,30.459999,30.520000,30.321953,2184800.0,CNP
2022-12-29,30.700001,30.830000,30.420000,30.480000,30.282211,2984200.0,CNP
2022-12-30,30.450001,30.510000,29.719999,29.990000,29.795391,2908400.0,CNP

In [32]:
df.Symbol.unique()

array(['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ATVI', 'ADM', 'ADBE', 'ADP',
       'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE',
       'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN',
       'AMCR', 'AMD', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK',
       'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA',
       'AAPL', 'AMAT', 'APTV', 'ACGL', 'ANET', 'AJG', 'AIZ', 'T', 'ATO',
       'ADSK', 'AZO', 'AVB', 'AVY', 'BKR', 'BALL', 'BAC', 'BBWI', 'BAX',
       'BDX', 'WRB', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BK', 'BA',
       'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BG',
       'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL',
       'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 'CNP'],
      dtype=object)

In [33]:
df2 = pd.DataFrame()

for i in range(0, len(list(df.Symbol.unique()))):
  df1 = df.query(f"Symbol == '{list(df.Symbol.unique())[i]}'")
  df2 = pd.concat([df1, df2])

df_port = pd.DataFrame()

for symbol in list(df.Symbol.unique()):
  df_symbol = df2.loc[df2["Symbol"] == symbol, ["Close"]]
  df_symbol = df_symbol.rename(columns={"Close": symbol})
  df_port = df_port.merge(df_symbol, how="outer", left_index=True, right_index=True)

df_port = df_port[list(df.Symbol.unique())]

In [34]:
df_port

,MMM,AOS,ABT,ABBV,ACN,ATVI,ADM,ADBE,ADP,AAP,...,CCL,CARR,CTLT,CAT,CBOE,CBRE,CDW,CE,CNC,CNP
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-02,83.370003,5.875000,20.986116,NaN,25.920000,3.523125,15.270000,19.549999,31.690842,27.139999,...,39.820000,NaN,NaN,41.325001,NaN,NaN,NaN,NaN,3.596250,9.720000
2004-01-05,84.959999,5.915000,20.986116,NaN,26.660000,3.502500,15.410000,19.900000,32.626656,26.893333,...,40.430000,NaN,NaN,42.450001,NaN,NaN,NaN,NaN,3.563750,9.850000
2004-01-06,84.699997,5.853333,20.833490,NaN,26.350000,3.519375,15.450000,19.920000,32.935951,27.373333,...,40.750000,NaN,NaN,41.700001,NaN,NaN,NaN,NaN,3.438750,9.930000
2004-01-07,83.239998,5.818333,21.053452,NaN,25.750000,3.450000,15.250000,19.719999,32.761478,28.233334,...,40.830002,NaN,NaN,41.244999,NaN,NaN,NaN,NaN,3.373750,9.980000
2004-01-08,82.680000,5.800000,20.433968,NaN,24.889999,3.465000,15.200000,19.000000,32.698032,27.486668,...,41.240002,NaN,NaN,40.924999,NaN,NaN,NaN,NaN,3.343750,10.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,120.139999,56.900002,108.180000,163.100006,266.089996,75.949997,94.620003,338.450012,240.940002,143.279999,...,7.810000,41.790001,43.349998,239.869995,126.180000,76.669998,178.139999,102.559998,81.629997,30.690001
2022-12-27,120.220001,57.669998,108.570000,162.990005,265.309998,75.790001,95.910004,335.089996,241.029999,145.020004,...,7.670000,41.869999,43.320000,243.139999,126.370003,76.489998,178.990005,103.750000,81.580002,30.920000
2022-12-28,118.290001,56.770000,107.830002,162.229996,263.119995,76.050003,93.620003,328.329987,237.850006,145.300003,...,7.670000,40.959999,42.939999,239.380005,126.120003,75.410004,175.470001,100.500000,81.580002,30.520000
2022-12-29,120.570000,57.660000,110.309998,162.559998,268.380005,76.760002,93.120003,337.579987,240.619995,146.309998,...,8.080000,41.849998,45.259998,240.199997,127.180000,77.550003,179.860001,103.489998,81.720001,30.480000
2022-12-30,119.919998,57.240002,109.790001,161.610001,266.839996,76.550003,92.849998,336.529999,238.860001,147.029999,...,8.060000,41.250000,45.009998,239.559998,125.470001,76.959999,178.580002,102.239998,82.010002,29.990000

In [35]:
!pip install PyPortfolioOpt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: PyPortfolioOpt in /usr/local/lib/python3.9/dist-packages (1.5.4)
Requirement already satisfied: scipy<2.0,>=1.3 in /usr/local/lib/python3.9/dist-packages (from PyPortfolioOpt) (1.10.1)
Requirement already satisfied: cvxpy<2.0.0,>=1.1.10 in /usr/local/lib/python3.9/dist-packages (from PyPortfolioOpt) (1.2.3)
Requirement already satisfied: numpy<2.0.0,>=1.22.4 in /usr/local/lib/python3.9/dist-packages (from PyPortfolioOpt) (1.22.4)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.9/dist-packages (from PyPortfolioOpt) (1.4.4)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.9/dist-packages (from cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt) (2.0.12)
Requirement already satisfied: setuptools<=64.0.2 in /usr/local/lib/python3.9/dist-packages (from cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt) (63.4.3)
Requirement already satisfied: scs>=1.1.6 in /usr/local/lib/python3.9/dist-packages (from cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt) (3.2.2)
Requirement already satisfied: osqp>=0.4.1 in /usr/local/lib/python3.9/dist-packages (from cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt) (0.6.2.post0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.19->PyPortfolioOpt) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.19->PyPortfolioOpt) (2022.7.1)
Requirement already satisfied: qdldl in /usr/local/lib/python3.9/dist-packages (from osqp>=0.4.1->cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt) (0.1.5.post3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas>=0.19->PyPortfolioOpt) (1.15.0)

In [36]:
from pypfopt.expected_returns import mean_historical_return
from pypfopt.risk_models import CovarianceShrinkage

In [37]:
from pypfopt.efficient_frontier import EfficientFrontier

def MarkowitzResults(start_year, start_month):
  df3 = df.query(f"Date.dt.year == {start_year} and Date.dt.month == {start_month}")

  listaSymbols = list(df.Symbol.unique())
  listaVolumes = []

  for i in listaSymbols:
    volume_local = (df3.query(f"Symbol == '{i}'")['Volume']).sum()
    listaVolumes.append([i, volume_local])

  lista_ordenada = sorted(listaVolumes, key=lambda x: x[1], reverse=True)[0:10]

  listaSimbolos = []
  for i in range(0, len(lista_ordenada)):
    listaSimbolos.append(lista_ordenada[i][0])

  df2 = pd.DataFrame()

  for i in range(0, len(listaSimbolos)):
    df1 = df3.query(f"Symbol == '{listaSimbolos[i]}'")
    df2 = pd.concat([df1, df2])

  df_port = pd.DataFrame()

  for symbol in listaSimbolos:
      df_symbol = df2.loc[df2["Symbol"] == symbol, ["Close"]]
      df_symbol = df_symbol.rename(columns={"Close": symbol})
      df_port = df_port.merge(df_symbol, how="outer", left_index=True, right_index=True)

  df_port = df_port[listaSimbolos]
  df_port

  from pypfopt.expected_returns import mean_historical_return
  from pypfopt.risk_models import CovarianceShrinkage

  mu = mean_historical_return(df_port)
  S = CovarianceShrinkage(df_port).ledoit_wolf()

  from pypfopt.efficient_frontier import EfficientFrontier

  ef = EfficientFrontier(mu, S)
  weights = ef.max_sharpe()

  cleaned_weights = ef.clean_weights()

  df3 = df.query(f"Date.dt.year == {start_year} and Date.dt.month == {start_month+1}")
  precos_iniciais = []
  for i in listaSimbolos:
    precos_iniciais.append(int(df3.query(f"Symbol == '{i}'")['Close'].iloc[0]))

  precos_finais = []
  for i in listaSimbolos:
    precos_finais.append(int(df3.query(f"Symbol == '{i}'")['Close'].iloc[len(df3.query(f"Symbol == '{i}'")['Close'])-1]))

    peso_normal = []
    for i in range(0, 10):
      peso_normal.append(0.1)

  peso_normal = pd.Series(peso_normal) 

  retorno_normal = (sum(precos_finais*peso_normal) - sum(precos_iniciais*peso_normal))/sum(precos_iniciais*peso_normal)

  j = 0
  soma_final = 0
  for i in listaSimbolos:
    soma_final += cleaned_weights[i]*precos_finais[j]
    j += 1

  j1 = 0
  soma_inicial = 0
  for i in listaSimbolos:
    soma_inicial += cleaned_weights[i]*precos_iniciais[j1]
    j1 += 1

  retorno_markowitz = (soma_final - soma_inicial)/soma_inicial

  return retorno_markowitz

In [38]:
MarkowitzResults(2022, 1)

0.021771132706644006

In [39]:
import matplotlib.pyplot as plt

normal_list = []
markowitz_list = []
indice = []

for i in range(2004,2022):
  for j in range(1, 12):
    try:
      resultado = MarkowitzResults(i,j)
      markowitz_list.append(resultado*100)
      indice.append(str(i)+'-'+str(j))
    except:
      print(".")

.
.
.
.
.
.
.
.
.
.
.

In [40]:
import plotly.graph_objs as go

fig = go.Figure()

fig.add_trace(go.Scatter(x=indice, y=markowitz_list, mode='lines', name='Markowitz'))

fig.update_layout(title='Comparação entre Normal e Markowitz', xaxis_title='Índice', yaxis_title='Valores', legend=dict(x=0, y=1))

fig.show()

In [41]:
from statistics import mean

mean(markowitz_list)

1.4805960084090863